export enum UserRole {
  PLATFORM_ADMIN = "PLATFORM_ADMIN",
  ORG_OWNER = "ORG_OWNER",
  ORG_ADMIN = "ORG_ADMIN",
  ANALYST = "ANALYST",
  VIEWER = "VIEWER",
}

export enum SourceType {
  USER_INPUT = "USER_INPUT",
  IMPORT = "IMPORT",
  GIS_CADASTRE = "GIS_CADASTRE",
  PLANNING_DOCUMENT = "PLANNING_DOCUMENT",
  THIRD_PARTY_API = "THIRD_PARTY_API",
  SYSTEM_DERIVED = "SYSTEM_DERIVED",
  MANUAL_OVERRIDE = "MANUAL_OVERRIDE",
}

export enum StrategyType {
  FREE_MARKET_RENTAL = "FREE_MARKET_RENTAL",
  SUBSIDIZED_RENTAL = "SUBSIDIZED_RENTAL",
  STUDENT_HOUSING = "STUDENT_HOUSING",
  BUILD_TO_SELL = "BUILD_TO_SELL",
  MIXED_STRATEGY = "MIXED_STRATEGY",
}

export enum AcquisitionType {
  BUY = "BUY",
  LEASE = "LEASE",
  OPTION = "OPTION",
}

export enum OptimizationTarget {
  MIN_BREAK_EVEN_RENT = "MIN_BREAK_EVEN_RENT",
  MIN_BREAK_EVEN_SALES_PRICE = "MIN_BREAK_EVEN_SALES_PRICE",
  MIN_REQUIRED_EQUITY = "MIN_REQUIRED_EQUITY",
  MAX_SUBSIDY_ADJUSTED_IRR = "MAX_SUBSIDY_ADJUSTED_IRR",
  MAX_UNIT_COUNT = "MAX_UNIT_COUNT",
}

export enum ScenarioStatus {
  DRAFT = "DRAFT",
  READY = "READY",
  RUNNING = "RUNNING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  ARCHIVED = "ARCHIVED",
}

export enum ScenarioRunStatus {
  QUEUED = "QUEUED",
  RUNNING = "RUNNING",
  SUCCEEDED = "SUCCEEDED",
  FAILED = "FAILED",
  CANCELLED = "CANCELLED",
}

export enum ScenarioReadinessStatus {
  READY = "READY",
  READY_WITH_WARNINGS = "READY_WITH_WARNINGS",
  BLOCKED = "BLOCKED",
}

export enum ScenarioReadinessIssueSeverity {
  BLOCKING = "BLOCKING",
  WARNING = "WARNING",
}

export enum ScenarioReadinessIssueCode {
  MISSING_PARCEL = "MISSING_PARCEL",
  PARCEL_GROUP_RUN_UNSUPPORTED_V0 = "PARCEL_GROUP_RUN_UNSUPPORTED_V0",
  MISSING_LAND_AREA = "MISSING_LAND_AREA",
  MISSING_BUILDABILITY_INPUT = "MISSING_BUILDABILITY_INPUT",
  MISSING_COST_INPUT = "MISSING_COST_INPUT",
  MISSING_MARKET_RENT = "MISSING_MARKET_RENT",
  MISSING_SUBSIDIZED_RENT = "MISSING_SUBSIDIZED_RENT",
  MISSING_SUBSIDIZED_SHARE = "MISSING_SUBSIDIZED_SHARE",
  MISSING_STATE_SUBSIDY_STACK = "MISSING_STATE_SUBSIDY_STACK",
  MISSING_SALES_PRICE = "MISSING_SALES_PRICE",
  TEMPORARY_MIXED_STRATEGY = "TEMPORARY_MIXED_STRATEGY",
  MISSING_MIX_CONFIGURATION = "MISSING_MIX_CONFIGURATION",
}

export enum PlanningParameterKey {
  GRZ = "GRZ",
  GFZ = "GFZ",
  MAX_BGF_SQM = "MAX_BGF_SQM",
  MAX_HEIGHT_M = "MAX_HEIGHT_M",
  MAX_FLOORS = "MAX_FLOORS",
  MAX_UNITS = "MAX_UNITS",
  BUILDABLE_WINDOW = "BUILDABLE_WINDOW",
  PARKING_SPACES_PER_UNIT = "PARKING_SPACES_PER_UNIT",
  SUBSIDY_ELIGIBILITY = "SUBSIDY_ELIGIBILITY",
  RENT_CAP_EUR_SQM = "RENT_CAP_EUR_SQM",
  LOAN_CAP_PCT = "LOAN_CAP_PCT",
}

export enum PlanningParameterType {
  NUMBER = "NUMBER",
  BOOLEAN = "BOOLEAN",
  JSON = "JSON",
  GEOMETRY = "GEOMETRY",
}

export enum FinancingSourceType {
  STATE_SUBSIDY = "STATE_SUBSIDY",
  KFW = "KFW",
  FREE_FINANCING = "FREE_FINANCING",
  GRANT = "GRANT",
  EQUITY = "EQUITY",
}

export enum FundingProviderType {
  COMMERCIAL_BANK = "COMMERCIAL_BANK",
  STATE_SUBSIDY_BANK = "STATE_SUBSIDY_BANK",
  KFW = "KFW",
}

export enum FundingCategory {
  FREE_LOAN = "FREE_LOAN",
  STATE_SUBSIDY_LOAN = "STATE_SUBSIDY_LOAN",
  KFW_LOAN = "KFW_LOAN",
}

export enum MissingDataFlag {
  BUILDABLE_WINDOW = "BUILDABLE_WINDOW",
  GRZ = "GRZ",
  GFZ = "GFZ",
  AVG_UNIT_SIZE_SQM = "AVG_UNIT_SIZE_SQM",
  HARD_COST_PER_BGF_SQM = "HARD_COST_PER_BGF_SQM",
  FUNDING_STACK = "FUNDING_STACK",
}

export enum RunWarningCode {
  HEURISTIC_BUILDABILITY = "HEURISTIC_BUILDABILITY",
  HEURISTIC_COSTS = "HEURISTIC_COSTS",
  HEURISTIC_CAPITAL_STACK = "HEURISTIC_CAPITAL_STACK",
}
